default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: beepi_development
  username: postgres
  password: 

test:
  <<: *default
  database: beepi_test

production:
  primary:
    adapter: postgresql
    url: postgresql://be_epicc_user:RZjihVWhT9FpRkY5uW4nLMp5K0puEf6L@dpg-d19iug0dl3ps73cns8d0-a/be_epicc

  queue:
    adapter: postgresql
    url: postgresql://be_epicc_user:RZjihVWhT9FpRkY5uW4nLMp5K0puEf6L@dpg-d19iug0dl3ps73cns8d0-a/be_epicc
